name: admin_web_app
description: "تطبيق ويب لإدارة الشركات المستخدمة لتطبيق المخزن (تراخيص وإعدادات مركزية)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Utilities
  intl: ^0.20.1
  file_picker: ^8.1.6
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
